### ISSUE TITLE
[Bug] Inmanga parser don't work

### ISSUE THREAD

**Issue by eze92** [Creckeryop/NOBORU-parsers#11]
I tried refreshing the parsers but it would not be working, the page seems to work fine

https://inmanga.com/

**Comment by Creckeryop** [comment]
The parser works fine, isn't? I checked it on my ps vita, and it works

**Comment by eze92** [comment]
I tried today and now it goes, weird because yesterday morning it didn't work and the page did

**Comment by Creckeryop** [comment]
maybe API of this site was closed for a while. Hope problem solved
