### ISSUE TITLE
[Bug] Mangahub parser error

### ISSUE THREAD

**Issue by CallmeBK** [Creckeryop/NOBORU-parsers#12]
Ever since I updated to official release 0.86 I've been getting the parser error for all my favorites saved from Mangahub. Tried viewing the manga, downloading the manga etc... neither work anymore on my PS vita. The site itself seems to be working fine. 

I updated to 0.86 about a week ago now.

**Comment by Creckeryop** [comment]
mangaHub changed their API it's not NOBORU problem. I am sorry, can't do anything to make mangaHub work. All i can do right now it's recommend you to move on other source. I'm really sorry.

**Comment by CallmeBK** [comment]
Oh gotcha, I will do that then. Thanks for the quick reply!

**Comment by mightysashiman** [comment]
but didn't you write the the parser ? if they changed their API, shouldn't you be updating your parser to fit how to talk with the new API ?🤷‍♂️

**Comment by Creckeryop** [comment]
> but didn't you write the the parser ? if they changed their API, shouldn't you be updating your parser to fit how to talk with the new API ?🤷‍♂️

they changed a way to access their API, i can't do anything with that. Noboru needs javascript to get something from API, i really can't do anything with that. Maybe if someone port selenium to vita
![image](https://user-images.githubusercontent.com/25725992/122310294-82343380-cf29-11eb-9a9b-f0d19e21f040.png)

mangahub catalog will be disabled from Noboru
