### ISSUE TITLE
[Bug] Mangadex doesn't work

### ISSUE THREAD

**Issue by x149te** [Creckeryop/NOBORU-parsers#13]
Мангадекс не работает. Сайт лег, с этим ничего не поделать. Но сейчас идет какой-то открытый бета-тест нового сервера. Что-то там про API. Можно ли как-то подключить это дело или стоит дождаться полноценной работы сайта?

**Comment by Creckeryop** [comment]
Я думаю что стоит дождаться, когда mangadex полностью доработают API. А то я боюсь что придется каждый раз обновлять парсер. Также нужно будет проверить, возможно ли обновить парсер mangadex чтобы никто не потерял прогресса (скорее всего нет).

**Comment by KeroEnertia** [comment]
I'm not sure if you're still waiting for the api to develop, but is there an eta on the mangadex parser becoming functional again?

**Comment by Creckeryop** [comment]
I hope i will finish mangadex this week, i already done most (i've started when i saw your message)

**Comment by Creckeryop** [comment]
Don't know how it works, maybe there are some errors that I did not notice, test it now and report if you notice any errors
