### ISSUE TITLE
[Bug] https://scan-fr.cc/manga/dragon-ball-perfect-edition

### ISSUE THREAD

**Issue by nad45** [Creckeryop/NOBORU-parsers#18]
I can't read Dragon Ball perfect edition on scan-fr.cc.
I can't load any page on any chapter,  it stays stuck on "loading page" message
And I also can't download the chapters.
When at 2%, I have an error message : There is problem with connection. 

Every other mangas on scan-fr catalog work correctly.
I checked on the Internet site, it works Ok, chapters are still online

**Comment by Creckeryop** [comment]
Fixed in 504ed56a5dd3ecf530d650636731a96c00a31e20
