### ISSUE TITLE
Add lectortmo alias tumangaonline

### ISSUE THREAD

**Issue by eze92** [Creckeryop/NOBORU-parsers#6]
Friend first very good the last update the gender filters and the new interface work and look great, if at any time you get to implement the capcha I ask you to add this page https://lectortmo.com/ (it was the problem that You mentioned me once with this one) from me I already recommended all the pages in Spanish that I know, that you walk well and do a very good job again

**Comment by Creckeryop** [comment]
i don't think i can add lectortmo, in near feature, sorry.
