### ISSUE TITLE
Nhentai will not load manga

### ISSUE THREAD

**Issue by vissyciggy** [Creckeryop/NOBORU-parsers#8]
Hello! I seem to be having issues with Nhentai. It worked fine for awhile, but as of a few days ago: 

 -manga pages will not load, they instead sit endlessly on 'loading page...' 

-manga will not download. The download starts and then fails with a 'There is problems with connection!' message.

-thumbnails appear to be working perfectly.

Ive checked nhentai on two other devices as well as the vita's web browser and the site appears to work just fine. All other catalogs that i have used are working perfectly as well

I have also tried a reinstall of Noboru to no avail, in addition to testing the app on a few different wireless networks

If I can provide more information, I happily will. Thank you for the creation of this app, its wonderful other than this issue.

**Comment by Creckeryop** [comment]
You can give a star to the project, if i helped (it's not obligatory).

**Comment by vissyciggy** [comment]
It works! Thank you very much for the quick return! Ill gladly star ya!
