### ISSUE TITLE
Can't search on MangaDex

### ISSUE THREAD

**Issue by dnbass89** [Creckeryop/NOBORU-parsers#9]
So I go to search on Mangadex and it opens the browser to login. I login and it takes me back to Noboru and reopens the browser. However it then hangs and comes up with this error code:

 "Could not connect to network (C2-14931-8)"

Tried on two different networks, no idea what's going on. A few weeks ago before an update I could search Mangadex via id number, but not anymore.

**Comment by Creckeryop** [comment]
id searching on is now working like
`id:12345`

**Comment by Creckeryop** [comment]
Also, i think this error comes from browser, and i don't think that there will be a fix for this, my only advise is to reboot ps vita, until it works, my vita have no errors with login

**Comment by dnbass89** [comment]
Yeah searching by id works again now. Thanks buddy.
